# Generated by Django 2.2.1 on 2019-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poxa_crush', '0002_crush_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crush',
            name='signo',
            field=models.CharField(choices=[('aries', 'áries'), ('touro', 'touro'), ('gemios', 'gemios'), ('cancerr', 'câncer'), ('leão', 'leão'), ('virgem', 'virgem'), ('libra', 'libra'), ('escorpiao', 'escorpião'), ('sargitario', 'sargitario'), ('capricornio', 'capricórnio'), ('aquarios', 'aquários'), ('peixes', 'peixes')], max_length=2),
        ),
    ]
